language: php

before_script: 
  - composer require satooshi/php-coveralls
  - composer install --no-dev
  
php:
  - '5.6'
  - '7.0'
  - nightly

after_success:
  - travis_retry php vendor/bin/coveralls -v

